//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogStudio.Graph.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogStudio.Graph.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddGraph {
            get {
                object obj = ResourceManager.GetObject("AddGraph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddPage {
            get {
                object obj = ResourceManager.GetObject("AddPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export to CSV....
        /// </summary>
        internal static string ExportCSVFailed {
            get {
                return ResourceManager.GetString("ExportCSVFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File (*.csv)|*.csv.
        /// </summary>
        internal static string ExportCSVFilter {
            get {
                return ResourceManager.GetString("ExportCSVFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify file to export CSV data to....
        /// </summary>
        internal static string ExportCSVSpecifyFile {
            get {
                return ResourceManager.GetString("ExportCSVSpecifyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemoveGraph {
            get {
                object obj = ResourceManager.GetObject("RemoveGraph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemovePage {
            get {
                object obj = ResourceManager.GetObject("RemovePage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new graph to selected page..
        /// </summary>
        internal static string RES_ToolTipAddGraph {
            get {
                return ResourceManager.GetString("RES_ToolTipAddGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new page..
        /// </summary>
        internal static string RES_ToolTipAddPage {
            get {
                return ResourceManager.GetString("RES_ToolTipAddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected graph..
        /// </summary>
        internal static string RES_ToolTipRemoveGraph {
            get {
                return ResourceManager.GetString("RES_ToolTipRemoveGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected page..
        /// </summary>
        internal static string RES_ToolTipRemovePage {
            get {
                return ResourceManager.GetString("RES_ToolTipRemovePage", resourceCulture);
            }
        }
    }
}
